# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a8c3baa6cea323e825f56aafd633e466b86660c5a41615f4601216da93bcc25f720fd48e76d9fc0736b7ddf4285daedeb23fa067379dcd37ac32b8185e3c25a

test:
  secret_key_base: ecfe400e1d9b4e0424e5a4253afe0c3f917b64b3b23af8db9940a3847db4f98d4944ea55e95e3b0c539df781612b8ddc9ecb8937b8f23c71224de26db2125639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
